[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_coverage = "src/mock/|test/|script/"
optimizer = true
optimizer_runs = 200
via_ir = true
# For doing bytecode comparisons without the metadata hash at the end, uncomment this line:
# bytecode_hash = "none"

[rpc_endpoints]
arbsepolia = "${RPC_ARBSEPOLIA}"
avalanche = "${RPC_AVALANCHE}"
ethereum = "${RPC_ETHEREUM}"
fuji = "${RPC_FUJI}"
polygon = "${RPC_POLYGON}"
sepolia = "${RPC_SEPOLIA}"

[etherscan]
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#etherscan-api-key-settings
# also has optional url attribute
arbsepolia = { key = "${ARBISCAN_API_KEY}" }
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "${SNOWTRACE_AVALANCHE_URL}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
fuji = { key = "${SNOWTRACE_API_KEY}", url = "${SNOWTRACE_FUJI_URL}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 2

[invariant]
runs = 5            # default 256
depth = 1000        # default 500
show_metrics = true

[lint]
exclude_lints = [
  "mixed-case-function",
  "mixed-case-variable",
  "screaming-snake-case-immutable",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
