[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_coverage = "src/mock/|test/|script/"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
arbsepolia = "${RPC_ARBSEPOLIA}"
fuji = "${RPC_FUJI}"
polygon = "${RPC_POLYGON}"
avalanche = "${RPC_AVALANCHE}"
ethereum = "${RPC_ETHEREUM}"

[etherscan]
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#etherscan-api-key-settings
# also has optional url attribute
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbsepolia = { key = "${ARBISCAN_API_KEY}" }
fuji = { key = "${SNOWTRACE_API_KEY}", url = "${SNOWTRACE_FUJI_URL}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "${SNOWTRACE_AVALANCHE_URL}"}
ethereum = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
